The Nginx configure script should check whether 'ruby' is in PATH, otherwise passenger-config breaks.

diff --git a/ext/nginx/config b/ext/nginx/config
--- a/ext/nginx/config
+++ b/ext/nginx/config
@@ -1,6 +1,10 @@
 PATH="$ngx_addon_dir/../../bin:$PATH"
 export PATH
 
+if ! ruby -v >/dev/null 2>/dev/null; then
+    echo '*** ERROR: Cannot find the "ruby" command in $PATH. Please fix your $PATH. You can learn more about $PATH at: http://www.modrails.com/documentation/Users%20guide%20Apache.html#_the_path_environment_variable'
+fi
+
 if test "x$PASSENGER_LIBS" = "x" && ! passenger-config --compiled; then
     echo "*** The Phusion Passenger support files are not yet compiled. Compiling them for you... ***"
     echo "*** Running 'rake nginx CACHING=false' in $ngx_addon_dir... ***"
